apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::847744951474:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1F2X1OX5CO8CD
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::847744951474:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-21T20:27:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "230885"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 540c9ecd-e57e-4f5a-b005-e802b1c2b448
